apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  volumes:
    - name: logs
      hostPath:
        path: /var/log/bb
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,'echo "2013-3-03 14:27:33 [main] INFO  Main - Start" > /var/log/bb/busybox.log; i=0; while true; do echo "2013-3-03 14:27:33 [main] INFO  Main - Start $i" >> /var/log/bb/busybox.log; i=$((i+1)); sleep 1; done']
    volumeMounts:
      - name: logs
        mountPath: /var/log/bb
